include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_lambdas
    - use_if_null_to_convert_nulls_to_bools
    - use_string_buffers
